### ISSUE TITLE
Fixed Vulns not Closing in Jira

### ISSUE THREAD

**Issue by Mooey28** [tenable/integration-jira-cloud#102]
I've had the integration running now since 13 Feb, the initial load took just under 3 days to complete ingest of Tenable.io data into Jira (I've left the config to the default 30 days). I set a scheduled task to run it again each week (on 20 Feb was last scheduled run) which only then took 15 minutes to update, and I manually ran the task this morning 22 Feb too, again took about 15/20 mins or so.

However I have noticed no vulnerabilities are moving to be marked as Done/Closed/Resolved or to be updated with the Vulnerability State FIXED field value in Jira.

I've tried to cross-check in Tenable.io to confirm they aren't updating, so as an example (I've redacted the bits which could be sensitive, but I can confirm the hostname and IP details match across Jira and Tenable.io):

![image](https://user-images.githubusercontent.com/23654964/108722874-8623ec00-751b-11eb-80a3-31cf6b85be25.png)

The only thing I can see that seems suspect is the Tenable UUID for the asset with this hostname and IP address is different to what's printed in the Tenable Asset UUID file in Jira - not sure what's going on there? If I search for the Jira-listed UUID in Tenable.io (with or without the separating '-') then no assets exist!

**Comment by SteveMcGrath** [comment]
that would lead me to beleive that its a different asset between the two.  Asset UUIDs in IO are canonical and are the primary linkage within the platform.  If you are in an environment where hosts change IPs a lot, you can modify the sub-task matching logic by removing the IP address from the matching behavior:

```yaml
issue_types:
  - name: Task
    type: standard
    search:
      - Tenable Plugin ID
  - name: Sub-task
    type: subtask
    search:
      - Tenable Platform
      - Tenable Plugin ID
      - Tenable Asset UUID
      - Vulnerability Port
      - Vulnerability Protocol
```
