### ISSUE TITLE
Running into issues while installing tenable-jira config.yaml ?

### ISSUE THREAD

**Issue by pre2500** [tenable/integration-jira-cloud#103]
Running into issues when running the config.yaml. Not sure where to troubleshoot.

**_Below is the error log_**

Traceback (most recent call last):
  File "/home/centos/tester/bin/tenable-jira", line 11, in <module>
    load_entry_point('tenable-jira-cloud==1.1.19', 'console_scripts', 'tenable-jira')()
  File "/home/centos/tester/lib64/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/centos/tester/lib64/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/centos/tester/lib64/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/centos/tester/lib64/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/centos/tester/lib64/python3.6/site-packages/tenable_jira/cli.py", line 204, in cli
    ingest.ingest(observed_since)
  File "/home/centos/tester/lib64/python3.6/site-packages/tenable_jira/transform.py", line 543, in ingest
    tags=tags
  File "/home/centos/tester/lib64/python3.6/site-packages/tenable/io/exports.py", line 439, in assets
    payload['filters'][option] = self._check(option, kw[option], int)
  File "/home/centos/tester/lib64/python3.6/site-packages/tenable/base/v1.py", line 271, in _check
    **expected_type.__name__ if hasattr(expected_type, '__name__') else expected_type
TypeError: updated_at is of type method.  Expected int.**

**_Below is my cleaned up config.yaml_**
```
tenable:
  # Tenable.io or API Access Key
  access_key: removed

  # Tenable.io or API Secret Key
  secret_key: removed

jira:
  # The API Token to use to authenticate to the Jira application
  api_token: removed

  # The User that will be authenticaing to the Jira application
  api_username: removed

  # The address pointing to the Jira application.
  address: removed

project:
  # The lead account id for the primary user for the project.
  leadAccountId: removed

# The following log definitions are optional.  Only specify these if you want
# to change the default logging behavior of only outputting warnings and errors
# to the screen.
log:
  # What is the logging level desired?  Available levels are:
  #   debug, info, warn, error
  # The default level if unspecified is "warn"
  level: warn

  # If you would like the log output to goto a file instead of standard output,
  # then specify the filename here:
  filename: /home/centos/tester/logfile.log

# The following section is optional.  You should only specify this section if
# you would like the bridge to run as a service with it's own timer.
service:
  # How many hours should we wait between jobs?  Note setting this to a
  # non-zero number will result in imports past the initial import will use
  # time of the last completed import as the basis for last observed.
  interval: 24



```
