### ISSUE TITLE
Can we add custom fields values in config.yaml ?

### ISSUE THREAD

**Issue by pre2500** [tenable/integration-jira-cloud#141]
Tried installing the plugin , it was able to create the project , but there is a mandatory field that we have setup in our JIRA . Is it  possible to populate the value in config.yaml

Below is the error message
body=b'{"errorMessages":[],"errors":{"customfield_10101":"Teams is required."}}'

**Comment by SteveMcGrath** [comment]
The code today doesn't support a static field, however it may be easy enough to add.

**Comment by pre2500** [comment]
@SteveMcGrath Thanks for the response, do let us know when you add it , we will be more than happy to test it..

**Comment by SteveMcGrath** [comment]
To use this in its current form, you would make the following additions to your config:

1. Add the custom field definition

```yaml
custom_fields:
  - jira_field: Static Test
    type: readonlyfield
    searcher: textsearcher
    issue_type:
      - Sub-task
    static_value: This is a test
```

2. Make sure the field is in the appropriate screen tab.  This will require copying the existing config from the vendored yaml and adding your field name to it:

```yaml
screen:
  tabs:
    Asset:
      - Tenable Asset UUID
      - Tenable Asset Tags
      - Tenable Platform
      - Device Hostname
      - Device NetBIOS Name
      - Device DNS Name
      - Device IPv4 Addresses
      - Device IPv6 Addresses
      - Device MAC Addresses
      - Device Network ID
      - Vulnerability Repository ID
      - Vulnerability Repository Name
      - Static Test
```
