### ISSUE TITLE
ERROR CANNOT CLOSE issue as no transitions were found.

### ISSUE THREAD

**Issue by art-tykh** [tenable/integration-jira-cloud#152]
Hi,

I have an issue with the latest **Tenable for Jira Cloud** plugin version.

I am receiving the following error messages:

`tenable_jira.transform.Tio2Jira ERROR CANNOT CLOSE VULN-<ISSUEID> as no transitions were found. [
  {
    "id": "5011",
    "name": "In Progress",
    "to": {
      "self": "https://company_name.atlassian.net/rest/api/3/status/10206",
      "description": "",
      "iconUrl": "https://company_name.atlassian.net/",
      "name": "In Progress",
      "id": "10206",
      "statusCategory": {
        "self": "https://company_name.atlassian.net/rest/api/3/statuscategory/4",
        "id": 4,
        "key": "indeterminate",
        "colorName": "yellow",
        "name": "In Progress"
      }
    },
    "hasScreen": false,
    "isGlobal": false,
    "isInitial": false,
    "isAvailable": true,
    "isConditional": false,
    "isLooped": false
  },
  {
    "id": "1001",
    "name": "Exception",
    "to": {
      "self": "https://company_name.atlassian.net/rest/api/3/status/10164",
      "description": "(Migrated on 17 May 2021 12:29 UTC)",
      "iconUrl": "https://company_name.atlassian.net/images/icons/statuses/generic.png",
      "name": "Exception",
      "id": "10164",
      "statusCategory": {
        "self": "https://company_name.atlassian.net/rest/api/3/statuscategory/1",
        "id": 1,
        "key": "undefined",
        "colorName": "medium-gray",
        "name": "No Category"
      }
    },
    "hasScreen": false,
    "isGlobal": false,
    "isInitial": false,
    "isAvailable": true,
    "isConditional": false,
    "isLooped": false
  },
  {
    "id": "2001",
    "name": "Resolve",
    "to": {
      "self": "https://company_name.atlassian.net/rest/api/3/status/5",
      "description": "A resolution has been taken, and it is awaiting verification by reporter. From here issues are either reopened, or are closed.",
      "iconUrl": "https://company_name.atlassian.net/images/icons/statuses/resolved.png",
      "name": "Resolved",
      "id": "5",
      "statusCategory": {
        "self": "https://company_name.atlassian.net/rest/api/3/statuscategory/3",
        "id": 3,
        "key": "done",
        "colorName": "green",
        "name": "Done"
      }
    },
    "hasScreen": false,
    "isGlobal": false,
    "isInitial": false,
    "isAvailable": true,
    "isConditional": false,
    "isLooped": false
  }
]"`

My **workflow schema** is as follows:
<img width="554" alt="Screenshot 2021-11-17 at 17 01 01" src="https://user-images.githubusercontent.com/1598859/142225199-8179b7dd-6029-49aa-a8ce-dd38d0c57bce.png">

**Plugin config**:
```
        tenable:
          access_key: <REDACTED>
          secret_key: <REDACTED>
          tio_severities:
            - critical
            - high
            - medium
        jira:
          api_token: <REDACTED>
          api_username: <REDACTED>
          address: <REDACTED>.atlassian.net
        issue_types:
          - name: Task
            jira_id: 10002
            type: standard
            search:
              - Tenable Plugin ID
          - name: Sub-task
            jira_id: 10003
            type: subtask
            search:
              - Tenable Platform
              - Tenable Plugin ID
              - Tenable Asset UUID
              - Device IPv4 Addresses
              - Device IPv6 Addresses
              - Vulnerability Port
              - Vulnerability Protocol
        project:
          leadAccountId: <REDACTED>
        log:
          level: warn
        service:
          interval: 1
```

Could, you, please, suggest what could be the root cause of the issue?

Thanks
