### ISSUE TITLE
Import "Informational" Tenable Scan Results?

### ISSUE THREAD

**Issue by atutrone** [tenable/integration-jira-cloud#155]
Is there a way to import results that are flagged as Informational through Tenable?  Right now, we have it configured to import every level, from low to critical, but don't see any way to add informational to the config file.

Thanks!

**Comment by SteveMcGrath** [comment]
I warn you infos have no vulnerability associated to them, and are simply metadata about the host/scan.  it'll also take a lot longer to run as well...that being said, you can add this to the config:

```yaml
tenable:
  tio_severities:
    - info
    - low
    - medium
    - high
    - critical
```
