### ISSUE TITLE
Ability to Customize Jira Issue Creator / Reporter?

### ISSUE THREAD

**Issue by bmcmahon-fa** [tenable/integration-jira-cloud#166]
**Summary**: I've attempted to update the YAML config with a custom creator / reporter -- each with the same **accountId** and **emailAddress** -- as reported by the layout of the API in the expanded fields of an issue; ex: _https://mycompany.net/rest/api/2/issue/VULN-6677?expand=names_
...but I honestly wasn't sure if that was even supported or not in this format:

```
jira:
  # The API Token to use to authenticate to the Jira application
  api_token: REDACTED

  # The User that will be authenticaing to the Jira application
  api_username: token.holder@mycompany.net

  # The address pointing to the Jira application.
  address: mycompany.net

project:
  # The lead account id for the primary user for the project.
  leadAccountId: _the_new_accountid_i_want_to_use_

creator:
  # The creator account id and email for the primary user on the project.
  accountId: _the_new_accountid_i_want_to_use_
  emailAddress: new.account@mycompany.net

reporter:
  # The reporter account id and email for the primary user on the project.
  accountId: _the_new_accountid_i_want_to_use_
  emailAddress: new.account@mycompany.net
```

However, it doesn't appear to be working, and the API token account holder continues to show up as the reporter and creator for any new issues created or existing issues updated. The jobs still run without issue, so I assume my custom fields and values are simply ignored or skipped over if they aren't interpreted correctly. Is there a way to modify the YAML config to support a custom creator and reporter as opposed to the API token holder for newly created or updated issues in Jira?
