### ISSUE TITLE
TypeError: argument of type 'NoneType' is not iterable

### ISSUE THREAD

**Issue by kraanvelt** [tenable/integration-jira-cloud#195]
I just overcame the screens/jira_ids issue after specifying the screens in the _config.yaml_ file. Now I receive the following error: **TypeError: argument of type 'NoneType' is not iterable**

**config.yaml:**
```yaml
tenable:
  access_key: ################################################################
  secret_key: ################################################################
  tio_severities:
    - high
    - critical
    - medium
    - low

jira:
  api_token: #####################
  api_username: ###########@###.com
  address: ##########.atlassian.net

project:
  leadAccountId: ########################

screen:
jira_ids:
- 10070
- 10072

log:
  level: debug
```

Extract of output, skipping INFO lines:
2022-08-15 10:29:37,082 root DEBUG Severity Prioritization set to: {'critical': 1, 'high': 2, 'medium': 3, 'low': 4}
2022-08-15 10:29:37,082 tenable.io.TenableIO DEBUG Request: {"method": "GET", "url": "https://cloud.tenable.com/session", "params": {}, "body": {}}
2022-08-15 10:29:37,082 urllib3.connectionpool DEBUG Starting new HTTPS connection (1): cloud.tenable.com:443
2022-08-15 10:29:37,435 urllib3.connectionpool DEBUG https://cloud.tenable.com:443 "GET /session HTTP/1.1" 200 None
2022-08-15 10:29:37,435 tenable_jira.jira.Jira DEBUG Request: {"method": "GET", "url": "https://company.atlassian.net/rest/api/3/project/VULN", "params": {}, "body": {}}
2022-08-15 10:29:37,435 urllib3.connectionpool DEBUG Starting new HTTPS connection (1): company.atlassian.net:443
2022-08-15 10:29:37,721 urllib3.connectionpool DEBUG https://company.atlassian.net:443 "GET /rest/api/3/project/VULN HTTP/1.1" 200 None
2022-08-15 10:29:37,768 tenable_jira.jira.Jira DEBUG Request: {"method": "GET", "url": "https://company.atlassian.net/rest/api/3/field", "params": {}, "body": {}}
2022-08-15 10:29:38,005 urllib3.connectionpool DEBUG https://company.atlassian.net:443 "GET /rest/api/3/field HTTP/1.1" 200 None
2022-08-15 10:29:38,005 tenable_jira.jira.Jira DEBUG Request: {"method": "GET", "url": "https://company.atlassian.net/rest/api/3/project/VULN", "params": {}, "body": {}}
2022-08-15 10:29:38,185 urllib3.connectionpool DEBUG https://company.atlassian.net:443 "GET /rest/api/3/project/VULN HTTP/1.1" 200 None
2022-08-15 10:29:38,185 tenable_jira.jira.Jira DEBUG Request: {"method": "GET", "url": "https://company.atlassian.net/rest/api/3/issuetype/project", "params": {"projectId": "10127"}, "body": {}}
2022-08-15 10:29:38,337 urllib3.connectionpool DEBUG https://company.atlassian.net:443 "GET /rest/api/3/issuetype/project?projectId=10127 HTTP/1.1" 200 None
2022-08-15 10:29:38,337 tenable_jira.transform.Tio2Jira DEBUG Issuetypes standard={'name': 'Task', 'jira_id': 10001, 'type': 'standard', 'search': ['Tenable Plugin ID']}, subtask={'name': 'Sub-task', 'jira_id': 10002, 'type': 'subtask', 'search': ['Tenable 
Platform', 'Tenable Plugin ID', 'Tenable Asset UUID', 'Vulnerability Port', 'Vulnerability Protocol']}
Traceback (most recent call last):
  File "C:\Python310\Scripts\tenable-jira-script.py", line 33, in <module>
    sys.exit(load_entry_point('tenable-jira-cloud==1.2.3', 'console_scripts', 'tenable-jira')())
  File "C:\Python310\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\Python310\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\Python310\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Python310\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\Python310\lib\site-packages\tenable_jira\cli.py", line 148, in cli
    ingest = Tio2Jira(source, jira, config)
  File "C:\Python310\lib\site-packages\tenable_jira\transform.py", line 69, in __init__
    self.screen_builder()
  File "C:\Python310\lib\site-packages\tenable_jira\transform.py", line 79, in screen_builder
    if not ('no_create' in self.config['screen']):
TypeError: argument of type 'NoneType' is not iterable

**Comment by SteveMcGrath** [comment]
your screen definition isn't indented.

```yaml
screen:
  jira_ids:
    - 10070
    - 10072
```
