### ISSUE TITLE
Error The priority selected is invalid

### ISSUE THREAD

**Issue by MelvinVMathew** [tenable/integration-jira-cloud#230]
2023-08-04 03:04:12,101 restfly.errors.BadRequestError ERROR [400: POST] [https://abc.atlassian.net/rest/api/3/issue?update_history=False](https://protect-us.mimecast.com/s/8Ar2C4xJQRtl84vgFMLqxM?domain=abc.atlassian.net) body=b'{"errorMessages":[],"errors":{"priority":"The priority selected is invalid."}}'

It seems that in our Jira environment there is no priority with ID:1. The ones we have are,
 
Critical - 2
Major - 3
Minor - 4
Needs Defined - 5
Blocker – 6

How can we modify the script to use Priority with ID 2 rather than ID 1?

**Comment by rishuzz** [comment]
HI @MelvinVMathew you can define this mapping in config 
```
 tenable: 
  severity_prioritization:
      critical: 1
      high: 2
      medium: 3
      low: 4
```
