### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by prikshitpathania** [tenable/integration-jira-cloud#233]
After the setup, on the first run we are getting below error, let me know how to resolve this one:

Traceback (most recent call last):
  File "/tenable/bin/tenable-jira", line 11, in <module>
    load_entry_point('tenable-jira-cloud==1.2.3', 'console_scripts', 'tenable-jira')()
  File "/tenable/lib64/python3.6/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/tenable/lib64/python3.6/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/tenable/lib64/python3.6/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/tenable/lib64/python3.6/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/tenable/lib64/python3.6/site-packages/tenable_jira/cli.py", line 218, in cli
    ingest.ingest(since, first_discovery)
  File "/tenable/lib64/python3.6/site-packages/tenable_jira/transform.py", line 736, in ingest
    self.create_issues(vulns)
  File "/tenable/lib64/python3.6/site-packages/tenable_jira/transform.py", line 529, in create_issues
    self._process_open_vuln(v, fid)
  File "/tenable/lib64/python3.6/site-packages/tenable_jira/transform.py", line 400, in _process_open_vuln
    issue, subissue, jql, sjql = self._process_vuln(vuln, fid)
  File "/tenable/lib64/python3.6/site-packages/tenable_jira/transform.py", line 254, in _process_vuln
    'issuetype = "{}"'.format(self.subtask['name']),
TypeError: 'NoneType' object is not subscriptable

Please help to understand this issue.

**Comment by prikshitpathania** [comment]
@SteveMcGrath  are you still available to help, or can you put me to right direction?

**Comment by prikshitpathania** [comment]
After troubleshooting it further, this is the issue we are getting now

2023-11-03 05:06:52,440 restfly.errors.BadRequestError ERROR [400: POST] https://algosec.atlassian.net/rest/api/3/issue?update_history=False body=b'{"errorMessages":[],"errors":{"priority":"The priority selected is invalid."}}'

**Comment by rishuzz** [comment]
Below are some points mentioned that can cause an above issue

1. The 'issue create screen' does not have priority fields [Can you please verify it by clicking on create jira ticket in that project and check whether a priority field is available or not]
2.  The priority mapping might be misconfigured, either remove the below config or add proper mapping for priority
<img width="404" alt="image" src="https://github.com/tenable/integration-jira-cloud/assets/4577844/715d039d-d4a0-428e-ac8b-fdb20d612769">

**Comment by prikshitpathania** [comment]
@rishuzz yes, we have the priority fields on Issue create screen.
and this is what I have added in config.yaml as per our Jira ID's
![image](https://github.com/tenable/integration-jira-cloud/assets/147366805/e47c392c-6a66-486d-9577-11ce66ca0579)

severity_prioritization:
    Critical: 10100
    High: 10000
    Medium: 10001
    Low: 10002

**Comment by SteveMcGrath** [comment]
Is `severity_prioritization` itself under the `tenable` stanza as @rishuzz had shown?

**Comment by prikshitpathania** [comment]
this is what it looks like

tenable:
  platform: tenable.sc
  address: tenable.company.com
  query_id: 1347

   access_key: 5ad832153f6e46faa72a656xxxxx
   secret_key: e5e4a071ce794d3281dd475xxxxx

severity_prioritization:
    Critical: 10100
    High: 10000
    Medium: 10001
    Low: 10002

**Comment by SteveMcGrath** [comment]
Please use lowercase for severity.

```yaml
tenable:
  platform: tenable.sc
  address: tenable.company.com
  query_id: 1347

  access_key: 5ad832153f6e46faa72a656xxxxx
  secret_key: e5e4a071ce794d3281dd475xxxxx

  severity_prioritization:
    critical: 10100
    high: 10000
    medium: 10001
    low: 10002
```

If you look at the bundled default config, you can see its all lowercase.

https://github.com/tenable/integration-jira-cloud/blob/master/tenable_jira/config.py#L50-L54

**Comment by prikshitpathania** [comment]
strange but after editing it got error 

Traceback (most recent call last):
  File "/tenable.jira/bin/tenable-jira", line 11, in <module>
    load_entry_point('tenable-jira-cloud==1.2.3', 'console_scripts', 'tenable-jira')()
  File "/tenable.jira/lib64/python3.6/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/tenable.jira/lib64/python3.6/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/tenable.jira/lib64/python3.6/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/tenable.jira/lib64/python3.6/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/tenable.jira/lib64/python3.6/site-packages/tenable_jira/cli.py", line 67, in cli
    config_from_file = yaml.safe_load(configfile)
  File "/tenable.jira/lib64/python3.6/site-packages/yaml/__init__.py", line 125, in safe_load
    return load(stream, SafeLoader)
  File "/tenable.jira/lib64/python3.6/site-packages/yaml/__init__.py", line 81, in load
    return loader.get_single_data()
  File "/tenable.jira/lib64/python3.6/site-packages/yaml/constructor.py", line 49, in get_single_data
    node = self.get_single_node()
  File "/tenable.jira/lib64/python3.6/site-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "/tenable.jira/lib64/python3.6/site-packages/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "/tenable.jira/lib64/python3.6/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/tenable.jira/lib64/python3.6/site-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/tenable.jira/lib64/python3.6/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/tenable.jira/lib64/python3.6/site-packages/yaml/composer.py", line 127, in compose_mapping_node
    while not self.check_event(MappingEndEvent):
  File "/tenable.jira/lib64/python3.6/site-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
  File "/tenable.jira/lib64/python3.6/site-packages/yaml/parser.py", line 428, in parse_block_mapping_key
    if self.check_token(KeyToken):
  File "/tenable.jira/lib64/python3.6/site-packages/yaml/scanner.py", line 116, in check_token
    self.fetch_more_tokens()
  File "/tenable.jira/lib64/python3.6/site-packages/yaml/scanner.py", line 223, in fetch_more_tokens
    return self.fetch_value()
  File "/tenable.jira/lib64/python3.6/site-packages/yaml/scanner.py", line 579, in fetch_value
    self.get_mark())
yaml.scanner.ScannerError: mapping values are not allowed here
  in "config.yaml", line 6, column 14

**Comment by SteveMcGrath** [comment]
Ok, can you dump your entire config in here?  obviously clearing out secrets.  also be sure to wrap your config in a yaml code block using backticks like so:

````
```yaml
tenable:
  platform: tenable.sc
  address: tenable.company.com
  query_id: 1347

  access_key: 5ad832153f6e46faa72a656xxxxx
  secret_key: e5e4a071ce794d3281dd475xxxxx

  severity_prioritization:
    critical: 10100
    high: 10000
    medium: 10001
    low: 10002
```
````

**Comment by prikshitpathania** [comment]
```yaml
tenable:
  platform: tenable.sc
  address: tenable.company.com
  query_id: 1347

   access_key: 5ad832153f6e46faa72a656xxxxxx

   secret_key: e5e4a071ce794d3281dd4757axxxxx

severity_prioritization:
    critical: 10100
    high: 10000
    medium: 10001
    low: 10002


jira:

  api_token: nzJ2W7p3jFuRAqxxxxxxx
  api_username: service@company.com
  address: company.atlassian.net

project:
  leadAccountId: 6368aab84bca781xxxxxxx

screen:
   jira_ids:
   - 10554
   - 10555

log:
  level: debug
  filename: /logfile.log


service:
  interval: 24
```

**Comment by SteveMcGrath** [comment]
try this instead.  Your spacing was off and your prioritization stanza was a root level (not under tenable).  I just took your config and reformatted to match what it shoudl look like.

```yaml
tenable:
  platform: tenable.sc
  address: tenable.company.com
  query_id: 1347
  access_key: 5ad832153f6e46faa72a656xxxxxx
  secret_key: e5e4a071ce794d3281dd4757axxxxx
  severity_prioritization:
    critical: 10100
    high: 10000
    medium: 10001
    low: 10002

jira:
  api_token: nzJ2W7p3jFuRAqxxxxxxx
  api_username: service@company.com
  address: company.atlassian.net

project:
  leadAccountId: 6368aab84bca781xxxxxxx

screen:
  jira_ids:
  - 10554
  - 10555

log:
  level: debug
  filename: /logfile.log

service:
  interval: 24
```
