### ISSUE TITLE
exploitable field

### ISSUE THREAD

**Issue by armada-lmt** [tenable/integration-jira-cloud#238]
I'm not seeing a field in the jira tickets that indicate if a vulnerability is exploitable or not.  This information is available in Tenable and it is currently used in our prioritization of resolution (we focus on exploitable vulnerabilities first).  Can this somehow be added?

**Comment by SteveMcGrath** [comment]
This can be added with a little tweaking of the config file.  What you would need to do is pull the field listing from the vendored config and then add in the field with the appropriate mapping:

For example:

```yaml
  - jira_field: Tenable Exploitable
    type: labels
    searcher: labelsearcher
    issue_type:
      - Sub-task
    tio_field: plugin.exploit_available
```
