### ISSUE TITLE
How to edit config.py

### ISSUE THREAD

**Issue by dzito-tenable** [tenable/integration-jira-cloud#24]
What steps need to be taken to modify config.py and have those changes reflected when running the integration?  I would like to modify the config.py file so that the integration will open tickets for low and medium vulns not just high and critical vulns.  It's not clear to me how to make those changes take effect.  Thank you.

**Comment by SteveMcGrath** [comment]
you do not modify the `config.py` file.  The `config.py` file is the _vendored defaults_.  If there is something you'd wish to override, then you must specify it within your config.  For example, to override the severity filter, you would add this into your tenable section like so:

```yaml
tenable:
  tio_severities:
    - low
    - medium
    - high
    - critical
```
