### ISSUE TITLE
Changing tio_severities

### ISSUE THREAD

**Issue by patelp132** [tenable/integration-jira-cloud#26]
I would like only the critical severity tickets being created in JIRA but when changing that in the script from:

tio_severities:
    - high
    - critical

to:

tio_severities:
    - critical

I am still seeing High severity items being pulled into JIRA. I tried moving this in the config.yaml as well but still the same issue.

**Comment by SteveMcGrath** [comment]
you would have to make sure you put it under the tenable declaration.  effectively right next to your api keys.

```yaml
tenable:
  access_key: XXXX
  secret_key: XXXX
  tio_severities:
    - critical
```

and remember that YAML is space/tab sensitive.  so make sure you use the same throughout.
