### ISSUE TITLE
Will this deployment remove/overwrite / or append an pre-existing VULN project board? 

### ISSUE THREAD

**Issue by MichaelTay0** [tenable/integration-jira-cloud#33]
The readme.md states "The integration creates a Vulnerability Management project using the project key VULN."

Right now our organization has a JIRA board with the key VULN.

Will this deployment remove/overwrite / or append an pre-existing VULN project board?

**Comment by SteveMcGrath** [comment]
add the key parameter into the project definition:

```yaml
project:
  key: TENB
  leadAccountId: 554433:00112233-ffee-aabb-aabb-998877665544
```
