### ISSUE TITLE
Enhancement: Replace DNS name with AWS Information

### ISSUE THREAD

**Issue by evazquez00** [tenable/integration-jira-cloud#69]
For cases where the AWS environment is extremely dynamic (CI/CD), it is more useful to have AWS Instance information as part of the Sub-Task name versus the DNS name.

For example, a current Sub-Task name starts with [ip-10-5-134-57.ec2.internal/0/TCP]

Instead of the relatively vague (and possible duplicate, depending on VPC subnetting) name, it would lend greater clarity to have the Sub-Task name start with: [icg-infra/prvamrptdomo/0/TCP].

That data is retrieved /documented in Tenable.io as:
AWS Instance Group Name and
AWS Name

The two fields are viewable in the "Asset > Additional Info" tab within Tenable.io, so it should be possible to retrieve them on an "if it exists" basis.

**Comment by SteveMcGrath** [comment]
The asset fields aren't currently being stored outside of the tags from the asset export.  these fields would need to be added and then merged into the asset sub-object to support this.

**Comment by SteveMcGrath** [comment]
Ok, to support this in 1.1.14, its just a matter of some config changes as the asset attributes you specify will be added to the vuln instances now.  You will first need to inform the integration what fields to store.  This is configurable as storing everything every time may be impactful to the memory of the host thats running the integration.  The below example is storing every AWS attribute thats available, however you can pair it down based on need.

```yaml
tenable:
  tio_asset_attr_cache:
  - aws_availability_zone
  - aws_ec2_instance_ami_id
  - aws_ec2_instance_group_name
  - aws_ec2_instance_id
  - aws_ec2_instance_state_name
  - aws_ec2_instance_type
  - aws_ec2_name
  - aws_ec2_product_code
  - aws_owner_id
  - aws_region
  - aws_subnet_id
  - aws_vpc_id
```

From there to change the summary declaration, you would need to modify the defaults.  To do so, you would need to add this to your config and adjust based on your needs.  for the example, i used the instance ID:

```yaml
issue_default_fields:
  summary:
    Sub-task:
      tio_field: '[{vuln[asset.aws_ec2_instance_id]}/{vuln[port.port]}/{vuln[port.protocol]}] [{vuln[plugin.id]}] {vuln[plugin.name]}'
```

Now, if you want these fields to be added to the asset tab in the issues themselves, you have a bit more work to do, but its doable.

1. You will need to replace the screen tab definition for the asset in your config.  Basically copy the list of attributes in there and then add the name of the attribute that you want added.  For example, I used (again) the instance ID:

https://github.com/tenable/integration-jira-cloud/blob/d45d86dc56f5ed4ca48bfbe6f77e58ee39630312/tenable_jira/config.py#L174-L215

```yaml
screen:
  tabs:
    Asset:
    - Tenable Asset UUID
    - Tenable Asset Tags
    - Tenable Platform
    - Device Hostname
    - Device NetBIOS Name
    - Device DNS Name
    - Device IPv4 Addresses
    - Device IPv6 Addresses
    - Device MAC Addresses
    - Device Network ID
    - Vulnerability Repository ID
    - Vulnerability Repository Name
    - AWS Instance ID
```

Note I'd using the human readable name, thats because the next phase is to add the field itself into the integration.  From this point the integration will start to track this custom field just like any other.

2. Add the custom field.  This one looks worse than it is.  You will need to copy into your config ALL of the fields in the field declaration, then add in yours at the end.

https://github.com/tenable/integration-jira-cloud/blob/d45d86dc56f5ed4ca48bfbe6f77e58ee39630312/tenable_jira/config.py#L217-L465

Then add the following:

```yaml
  - jira_field: AWS Instance ID
    type: labels
    searcher: labelsearcher
    issue_type:
    - Sub-Task
    tio_field: asset.aws_ec2_instance_id
```

Obviously, adding more fields is just a matter of continuing with those definitions.
