### ISSUE TITLE
Open issues in Jira but closed in Tenable.io

### ISSUE THREAD

**Issue by jimbrewster** [tenable/integration-jira-cloud#73]
Greetings,

We setup the tenable jira cloud integration a few weeks back and it appeared to be working well.  However after comparing open issues in the tenable.io portal to open issues in Jira, we see discrepancies.   There are VULN's in Jira that are open that no longer show up in the tenable.io portal.

**Comment by SteveMcGrath** [comment]
Have you looked at expanding the date range in IO beyond the default 30 days?

**Comment by jimbrewster** [comment]
Just gave that try, expanded the range to the ALL setting in IO.  Still see open VULs in Jira (qty 845) that are not shown in Tenable.io (qty 673).

**Comment by SteveMcGrath** [comment]
Is there anything in common with this vulns in the variance?  The integration is just taking the data from the vuln exports APIs and translating them into Jira tickets.  Maybe a call is needed to see whats going on?

**Comment by jimbrewster** [comment]
Many of the vuln names contain either a colon or less than sign.  Yes, happy to jump on a call if that would help diagnose the issue.

**Comment by SteveMcGrath** [comment]
Yeah throw me an email to smcgrath _at_ tenable.com and include the output of a `--troubleshoot` run as well.

**Comment by SteveMcGrath** [comment]
Looping back in to the issue ticket, the source of the issue may in-fact be that the IPs are changing on the hosts.  The default config for the integration is to uniquely identify for both SC and IO, however as you're using IO, you can remove a couple of the attributes used for filtering and allow it to be IO-specific.  To do so, you would past this into your running config, effectively overriding the default behavior.

```yaml
issue_types:
  - name: Task
    type: standard
    search:
      - Tenable Plugin ID
  - name: Sub-task
    type: subtask
    search:
      - Tenable Platform
      - Tenable Plugin ID
      - Tenable Asset UUID
      - Vulnerability Port
      - Vulnerability Protocol
```

Normally there would also be checks for IPv4 and IPv6 in the subtask, which we have removed here.
