### ISSUE TITLE
Is there a change that can be made in the config, to pull only "Exploit Available" vulns 

### ISSUE THREAD

**Issue by MichaelTay0** [tenable/integration-jira-cloud#74]
In the scenario where we want to only pull actively exploited vulns in the wild and populate a Jira board with only those vulnerability findings. 

Is there a change that can be made in the config, to pull only "Exploit Available" vulns 

my config.yaml looks a little like this to pull only vulns with a vpr of 6 or higher (i realize this does create orphan tickets)

```
tio_ignore_accepted: true
  tio_autoclose_accepted: true
  tio_vpr_thresh: 6.0
  tio_severities:
    - low
    - medium
    - high
    - critical
```
