### ISSUE TITLE
Got error -- AttributeError: 'str' object has no attribute 'get'

### ISSUE THREAD

**Issue by bhaskartelagi** [tenable/integration-jira-cloud#83]
Hi Team,

While implementing this project we got below error. We created a config.yaml file and supplied to the binary tenable-jira and got this error. 

 File "/home/jira-tenable/lib/python3.6/site-packages/tenable_jira/cli.py", line 70, in cli
    if config['tenable'].get('tio_transform_tags'):
AttributeError: 'str' object has no attribute 'get'

Please help us to resolve this. 

Regards,

**Comment by bhaskartelagi** [comment]
Hi Team,

Please help us on this issue. 

Regards,

**Comment by bhaskartelagi** [comment]
Hi Team,

Awaiting for your reply. 

Regards,

**Comment by SteveMcGrath** [comment]
@bhaskartelagi For reference, last week was a holiday week for most folks in the US.  Further continually pinging the issue doesn't escalate the order in which we can work on this issue.

Now to the issue at hand, can you provide more detail than the error message?  what does your configuration look like?

**Comment by bhaskartelagi** [comment]
@SteveMcGrath   I followed steps given at https://github.com/tenable/integration-jira-cloud/wiki for Ubuntu machine.   After all installation when i run the command "jira-tenable config.yaml" I got parsing error for config.yaml and I resolved the parsing error by changing spaces/indentation in config.yaml and then when executed same command we got that error "AttributeError: 'str' object has no attribute 'get'"

Am i doing it right ?

**Comment by bhaskartelagi** [comment]
tenable:
  access_key: XXXX
  secret_key: XXXX
jira:
  api_token: XXXX
  api_username: XXXX
  address: XXXX

project:
  leadAccountId: XXXX
log:
  filename: /var/log/logfile.log

service:
  interval: 1

**Comment by SteveMcGrath** [comment]
I'm assuming you mean like this:

```yaml
tenable:
    access_key: XXXX
    secret_key: XXXX

jira:
    api_token: XXXX
    api_username: XXXX
    address: XXXX

project:
    leadAccountId: XXXX

log:
    filename: /var/log/logfile.log

service:
    interval: 1
```
