### ISSUE TITLE
Config to filter by tag?

### ISSUE THREAD

**Issue by jrmcpeek** [tenable/integration-jira-cloud#97]
We're looking to use this tool and the way we have tenable.io setup is to have each of our assets tagged to the product it belongs to.

With different teams managing / remediating any vulnerabilities, is there a way to get the tool to pull based on matching one of those tags?

**Comment by jrmcpeek** [comment]
Found it in another issue after a deeper search.

```
tenable:
  tio_tags:
    - key: <key>
      value: <value>
```
